blog/blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^blog/', include('blog_app.urls')),
    url(r'^admin/', admin.site.urls),
]

blog/blog_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.RootRedirectView.as_view(), name='root_redirect'),
    path('all', views.AllView.as_view(), name='all'),
    path('feed', views.FeedView.as_view(), name='feed'),

    path('user/<int:profile_pk>/', views.BlogView.as_view(), name='blog'),
    path('user/<int:profile_pk>/following', views.FollowingView.as_view(),
         name='following'),
    path('user/<int:profile_pk>/follow', views.ProfileUpdateView.as_view(),
         name='manage_follow'),

    path('post/mark_as_read', views.ProfileUpdateView.as_view(),
         name='post_mark'),
    path('post/new', views.PostCreate.as_view(), name='post_create'),
    path('post/<int:pk>/', views.PostView.as_view(), name='post_detail'),
    path('post/<int:pk>/edit', views.PostUpdate.as_view(), name='post_update'),
    path('post/<int:pk>/del', views.PostDelete.as_view(), name='post_delete'),
]

blog/blog_app/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    following = models.ManyToManyField('self', symmetrical=False)
    posts_read = models.ManyToManyField('Post')

    def __str__(self):
        return f'{self.user.username} ({self.user.get_full_name()})'


class Post(models.Model):
    caption = models.CharField(max_length=128)
    content_text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.caption}: {self.content_text[:16]} ' \
               f'({self.author.user.username} - {self.pub_date})'

blog/blog_app/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied, ValidationError
from django.db.models.signals import m2m_changed, post_save
from django.dispatch import receiver
from django.http import Http404, HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic

from celery import group

from .models import Profile, Post
from .tasks import send_new_post_notification


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


@receiver(m2m_changed, sender=Profile.following.through)
def profile_update(sender, instance, action, pk_set, **kwargs):
    if action == 'pre_add':
        if instance.pk == list(pk_set)[0]:
            raise ValidationError('You can not follow yourself')
    elif action == 'post_remove':
        posts_read = instance.posts_read.filter(author__id__in=pk_set)
        instance.posts_read.remove(*posts_read)


@receiver(post_save, sender=Post)
def post_create_email_followers(sender, instance, created, **kwargs):
    if created:
        followers_email = list(
            Profile.objects.select_related('user')
                .filter(following=instance.author)
                .values_list('user__email', flat=True))

        path = str(reverse_lazy('post_detail', args=(instance.pk,)))

        send_tasks = group([
            send_new_post_notification.si(str(instance.author), path, email)
            for email in followers_email])
        send_tasks()


class BaseView(generic.base.ContextMixin):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_profile'] = (self.request.user.profile
                                   if self.request.user.is_authenticated
                                   else None)

        return context


class RootRedirectView(generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return (reverse_lazy('feed') if self.request.user.is_authenticated
                else reverse_lazy('all'))


class AllView(BaseView, generic.ListView):
    model = Post

    login_url = '/accounts/login/'

    template_name = 'blog_app/all_posts.html'
    context_object_name = 'posts_feed'
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.select_related('author').order_by('-pub_date')


class FeedView(LoginRequiredMixin, AllView):
    model = Post

    login_url = '/accounts/login/'

    template_name = 'blog_app/feed.html'
    context_object_name = 'posts_feed'

    def get_queryset(self):
        return (Post.objects.select_related('author')
                .filter(author__in=self.request.user.profile.following.all())
                .order_by('-pub_date'))


@method_decorator(login_required, name='dispatch')
class ProfileUpdateView(generic.UpdateView):
    model = Profile

    def _mark_post(self, user_profile, post_pk):
        post = get_object_or_404(Post, pk=post_pk)
        if post in user_profile.posts_read.all():
            user_profile.posts_read.remove(post)
        else:
            user_profile.posts_read.add(post)

    def _manage_follow(self, user_profile, follow, unfollow):
        profile = Profile.objects.get(pk=follow or unfollow)

        if user_profile == profile:
            return

        if follow:
            user_profile.following.add(profile)
        elif unfollow:
            user_profile.following.remove(profile)

    def get(self, request, *args, **kwargs):
        raise Http404

    def post(self, request, *args, **kwargs):
        if 'mark_post_read' in request.POST:
            self._mark_post(self.request.user.profile,
                            request.POST['mark_post_read'])
        elif 'follow' in request.POST or 'unfollow' in request.POST:
            self._manage_follow(
                self.request.user.profile,
                request.POST.get('follow'), request.POST.get('unfollow'))
        else:
            return HttpResponseBadRequest(f'Bad request: {request.path}')

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class BlogView(BaseView, generic.ListView):
    model = Post

    template_name = 'blog_app/blog.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        if not Profile.objects.filter(pk=self.kwargs['profile_pk']).exists():
            raise Http404(f'User profile with pk = {self.kwargs["profile_pk"]} '
                          f'does not exist.')
        return (Post.objects.filter(author__pk=self.kwargs['profile_pk'])
                .order_by('-pub_date'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        profile_pk = self.kwargs['profile_pk']
        profile = (Profile.objects.select_related('user').get(pk=profile_pk))

        context['user_info'] = {
            'username': profile.user.username,
            'full_name': profile.user.get_full_name,
            'postcount': profile.post_set.count(),
            'pk': profile_pk
        }

        if self.request.user.is_authenticated:
            context['is_followed'] = (self.request.user.profile
                                      .following.filter(pk=profile_pk).exists())

        return context


class FollowingView(BaseView, LoginRequiredMixin, generic.ListView):
    model = Profile

    template_name = 'blog_app/following.html'
    context_object_name = 'profiles'

    def get_queryset(self):
        return (self.request.user.profile.following.all()
                .order_by('user__username'))


class PostView(BaseView, generic.DetailView):
    model = Post

    template_name = 'blog_app/post_detail.html'
    context_object_name = 'post'


@method_decorator(login_required, name='dispatch')
class PostCreate(BaseView, generic.CreateView):
    model = Post
    fields = ['caption', 'content_text']

    def form_valid(self, form):
        form.instance.author = Profile.objects.get(user=self.request.user)
        form.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('post_detail', args=(self.object.pk,))


@method_decorator(login_required, name='dispatch')
class PostUpdate(BaseView, generic.UpdateView):
    model = Post
    fields = ['caption', 'content_text']

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().author.user != request.user:
            raise PermissionDenied

        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('post_detail', args=(self.object.pk,))


@method_decorator(login_required, name='dispatch')
class PostDelete(BaseView, generic.DeleteView):
    model = Post

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().author.user != request.user:
            raise PermissionDenied

        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy(
            'blog', args=(Profile.objects.get(user=self.request.user).pk,))

blog/blog_app/templates/blog_app/all_posts.html
{% extends "blog_app/base.html" %}

{% block title %}Все блоги{% endblock %}

{% block main_content %}
    {% for post in posts_feed %}
        <div class="post-container">
            <a href="{% url 'post_detail' post.pk %}">
                <h1 class="post-caption">{{ post.caption }}</h1>
            </a>
            <div class="content-container">
                <span class="post-content">
                    {% block post_content_block %}
                        {{ post.content_text|linebreaks }}
                    {% endblock %}
                </span>
            </div>
            <div class="post-footer">
                <div class="date-container">{{ post.pub_date|date:"j F (D) Y - H:i" }}</div>
                <div class="author-container">
                    <a href="{% url 'blog' post.author.user.profile.pk %}">
                        @{{ post.author.user.username }} ({{ post.author.user.get_full_name }})</a>
                </div>
                {% block mark_post_button %}{% endblock %}
            </div>
        </div>
    {% empty %}
        {% block empty_post_feed %}<p>Постов нет.</p>{% endblock %}
    {% endfor %}
{% endblock %}

blog/blog_app/templates/blog_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Blog{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab|Vollkorn" rel="stylesheet">
</head>
<body>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog_app/style.css' %}">

    <nav class="navbar">
        <a href="{% url 'all' %}">Все блоги</a>
        {% if user_profile %}
            <a href="{% url 'feed' %}">Лента</a>
            <a href="{% url 'blog' user_profile.pk %}">Мой блог</a>
            <a href="{% url 'post_create' %}">Написать пост</a>
            <a href="{% url 'following' user_profile.pk %}">Управление подписками</a>
            <a href="{% url 'logout' %}">Выйти</a>
        {% else %}
            <a href="{% url 'login' %}">Войти</a>
        {% endif %}
    </nav>

    <div class="blog-container">
        {% block header_content %}{% endblock %}
        <main>
            {% block main_content %}{% endblock %}
        </main>
        <br/>
        <footer>
            {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                        {% endif %}
                        <span class="page-current">
                            Страница: {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
        </footer>
    </div>
</body>
</html>

blog/blog_app/templates/blog_app/blog.html
{% extends "blog_app/base.html" %}

{% block title %}Блог{% endblock %}

{% block header_content %}
<header class="userinfo-header">
    <div class="username-container" id="blog-userfullname">{{ user_info.full_name }}</div>
    <div id="blog-postcount">Всего постов: {{ user_info.postcount }}</div>
    <div class="author-container" id="blog-username">@{{ user_info.username }}</div>
    {% if user_profile and user_info.pk != user_profile.pk %}
        <div id="blog-subscribe-button">
            <form action="{% url 'manage_follow' user_info.pk %}" method="post">{% csrf_token %}
                {% if is_followed %}
                    <button type="submit" name="unfollow" value="{{ user_info.pk }}">
                        Отписаться</button>
                {% else %}
                    <button type="submit" name="follow" value="{{ user_info.pk }}">
                        Подписаться</button>
                {% endif %}
            </form>
        </div>
    {% endif %}
</header>
{% endblock %}

{% block main_content %}
    {% for post in posts %}
        <div class="post-container">
            <a href="{% url 'post_detail' post.pk %}">
                <h1 class="post-caption">{{ post.caption }}</h1></a>
            <div class="content-container">
                <span class="post-content">{{ post.content_text|linebreaks }}</span>
            </div>
            <div class="post-footer">
                <div class="date-container">{{ post.pub_date|date:"j F (D) Y - H:i" }}</div>
            </div>
        </div>
    {% empty %}
        <p>В вашем блоге пока нет постов. Хотите <a href="{% url 'post_create' %}">написать</a>?</p>
    {% endfor %}
{% endblock %}

blog/blog_app/templates/blog_app/feed.html
{% extends "blog_app/all_posts.html" %}

{% block title %}Лента{% endblock %}

{% block post_content_block %}
    {% if user_profile and user_profile in post.profile_set.all %}
        {{ post.content_text|linebreaks|truncatewords:"64" }}
    {% else %}
        {{ post.content_text|linebreaks }}
    {% endif %}
{% endblock %}

{% block mark_post_button %}
    {% if user_profile %}
        <form action="{% url 'post_mark' %}" method="post">{% csrf_token %}
            <button type="submit" id="mark_post_{{ forloop.counter }}" name="mark_post_read" value="{{ post.pk }}">
                {% if user_profile and user_profile in post.profile_set.all %}
                    Отметить: не прочитано
                {% else %}
                    Отметить: прочитано
                {% endif %}
            </button>
    </form>
    {% endif %}
{% endblock %}

{% block empty_post_feed %}<p>В вашей ленте пока нет постов.</p>{% endblock %}

blog/blog_app/templates/blog_app/following.html
{% extends "blog_app/base.html" %}

{% block title %}Блог{% endblock %}

{% block header_content %}<h1>Вы подписаны на:</h1>{% endblock %}

{% block main_content %}
    {% for profile in profiles %}
        <div class="author-container">
            <a href="{% url 'blog' profile.pk %}">
                @{{ profile.user.username }} ({{ profile.user.get_full_name }})</a>
            <span style="font-style: normal">Постов: {{ profile.post_set.count }}</span>
            <form action="{% url 'manage_follow' profile.pk %}" method="post">{% csrf_token %}
                <button type="submit" name="unfollow" value="{{ profile.pk }}">
                    Отписаться</button>
            </form>
        </div>
    {% empty %}
        <p>Вы пока ещё ни на кого не подписаны.</p>
    {% endfor %}
{% endblock %}

blog/blog_app/templates/blog_app/post_confirm_delete.html
{% extends "blog_app/base.html" %}

{% block title %}Подтверждение удаления поста{% endblock %}

{% block header_content %}
    <p>Вы действительно хотите удалить пост?</p>
{% endblock %}

{% block main_content %}
    <form method="post">{% csrf_token %}
        <div class="post-container">
            <h1 class="post-caption">{{ object.caption }}</h1>
            <div class="content-container">
                <span class="post-content">{{ object.content_text|linebreaks }}</span>
            </div>
            <div class="post-footer">
                <div class="date-container">{{ object.pub_date }}</div>
            </div>
        </div>
        <input type="submit" value="Удалить">
    </form>
{% endblock %}

blog/blog_app/templates/blog_app/post_detail.html
{% extends "blog_app/base.html" %}

{% block title %}Пост{% endblock %}

{% block main_content %}
    <div class="post-container">
        <h1 class="post-caption">{{ post.caption }}</h1>
        <div class="content-container">
            <span class="post-content">{{ post.content_text|linebreaks }}</span>
        </div>
        <div class="post-footer">
            <div class="date-container">{{ post.pub_date|date:"j F (D) Y - H:i" }}</div>
            <div class="author-container">
                <a href="{% url 'blog' post.author.pk %}">
                    @{{ post.author.user.username }} ({{ post.author.user.get_full_name }})</a>
            </div>
            {% if user_profile == post.author %}
            <form action="{% url 'post_update' post.pk %}" method="get">
                <input type="submit" value="Редактировать"/>
            </form>
            <form action="{% url 'post_delete' post.pk %}" method="get">
                <input type="submit" value="Удалить"/>
            </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

blog/blog_app/templates/blog_app/post_form.html
{% extends "blog_app/base.html" %}

{% block title %}Новый пост{% endblock %}

{% block main_content %}
    <div class="post-container">
        <form method="post">
            {% csrf_token %}
            <div class="form-caption-container">
                <label for="{{ form.caption.id_for_label }}">Заголовок:</label><br>
                {{ form.caption.errors }}
                {{ form.caption }}
            </div>
            <div class="form-content-text-container">
                <label for="{{ form.content_text.id_for_label }}">Текст поста:</label><br>
                {{ form.content_text.errors }}
                {{ form.content_text }}
            </div>
            <input type="submit" value="Сохранить">
        </form>
    </div>
{% endblock %}

blog/blog_app/templates/blog_app/subscription.html
{% extends "blog_app/base.html" %}

{% block title %}Блог{% endblock %}

{% block header_content %}
    <h1>Вы подписаны на:</h1>
{% endblock %}

{% block main_content %}
    {% for profile in profiles %}
        <div class="author-container">
            <a href="{% url 'blog' profile.pk %}">
                @{{ profile.user.username }} ({{ profile.user.get_full_name }})</a>
            <span style="font-style: normal">Постов: {{ profile.post_set.count }}</span>
            <form action="{% url 'subscription' profile.pk %}" method="post">{% csrf_token %}
                <input type="submit" value="Отписаться">
            </form>
        </div>
    {% endfor %}
{% endblock %}